version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/devfolio
      - JWT_SECRET=your-super-secret-jwt-key
    depends_on:
      - mongo
    volumes:
      - ./Backend:/app
      - /app/node_modules
    networks:
      - devfolio-network
